<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Monashris-MBP" failures="2" tests="7" name="First6Run" time="51.046" errors="0" timestamp="2023-02-20T09:21:00 SGT">
  <testcase classname="assessmentmona.Verifybasics" name="verifyBasics" time="0.052"/>
  <testcase classname="assessmentmona.Verifyclick" name="verifyClick" time="0.379"/>
  <testcase classname="assessmentmona.VerifyaddRemoveitems" name="verifyaddRemoveitems" time="5.811"/>
  <testcase classname="assessmentmona.VerifycheckBox" name="verifycheckboxcheck" time="0.725"/>
  <testcase classname="assessmentmona.Verifybasicauth" name="verifybasicauthfail" time="0.642"/>
  <testcase classname="assessmentmona.Verifybasicauth" name="verifybasicauthsuccess" time="2.4">
    <failure type="java.lang.AssertionError" message="expected [Congratulations! You must have the proper credentials.] but found [The following error was encountered while trying to retrieve the URL: http://the-internet.herokuapp.com/basic_auth]">
      <![CDATA[java.lang.AssertionError: expected [Congratulations! You must have the proper credentials.] but found [The following error was encountered while trying to retrieve the URL: http://the-internet.herokuapp.com/basic_auth]
at assessmentmona.Verifybasicauth.verifybasicauthsuccess(Verifybasicauth.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifybasicauthsuccess -->
  <testcase classname="assessmentmona.Verifybasicauth" name="verifybasicauthsuccess" time="9.85">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at components.Baseclassutil.getscreenshot(Baseclassutil.java:37)
at components.Listeners.onTestFailure(Listeners.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifybasicauthsuccess -->
</testsuite> <!-- First6Run -->
